# =================================================================
# ██╗░░██╗██╗░░░██╗██████╗░██████╗░██╗░░░░░░█████╗░░█████╗░██╗░░██╗
# ██║░░██║╚██╗░██╔╝██╔══██╗██╔══██╗██║░░░░░██╔══██╗██╔══██╗██║░██╔╝
# ███████║░╚████╔╝░██████╔╝██████╔╝██║░░░░░██║░░██║██║░░╚═╝█████═╝░
# ██╔══██║░░╚██╔╝░░██╔═══╝░██╔══██╗██║░░░░░██║░░██║██║░░██╗██╔═██╗░
# ██║░░██║░░░██║░░░██║░░░░░██║░░██║███████╗╚█████╔╝╚█████╔╝██║░╚██╗
# ╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═╝░░╚═╝╚══════╝░╚════╝░░╚════╝░╚═╝░░╚═╝
# =================================================================


background {
    monitor =
    # Descarga un wallpaper similar y pon la ruta exacta aquí
    path = ~/.config/wallpapers/wallhaven-jevgyp_1920x1080.png
    blur_passes = 0 # En la imagen original no hay desenfoque
    color = rgba(25, 20, 20, 1.0)
}

# HORA
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M") </big></b>"
    color = rgba(255, 255, 255, 0.9)
    font_size = 90
    font_family = sans-serif # Si tienes instalada alguna fuente "Thin" o "Light", ponla aquí
    position = 0, 200
    halign = center
    valign = center
}

# SALUDO
label {
    monitor =
    # Puedes cambiarlo por "hi, $USER!" para que tome tu usuario del sistema automáticamente
    text = hi, Esteban!
    color = rgba(255, 255, 255, 0.7)
    font_size = 18
    font_family = sans-serif
    position = 0, 100
    halign = center
    valign = center
}

# CAJA DE CONTRASEÑA
input-field {
    monitor =
    size = 200, 45
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(20, 20, 30, 0.7) # Fondo oscuro y ligeramente transparente
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    placeholder_text = <span foreground="white" size="small"><i>Enter Password</i></span>
    hide_input = false
    position = 0, -250 # Lo empuja hacia la parte inferior
    halign = center
    valign = center
    rounding = 20 # Le da la forma de píldora redondeada
}
